stages:
   step_1_FlatsDataset_cleaning:
    cmd: python .\src\data\step_1_FlatsDataset_cleaning.py .\data\raw\flats.xlsx
    deps:
    - .\src\data\step_1_FlatsDataset_cleaning.py
    - .\data\raw\flats.xlsx
  
   step_2_Independent_HousesDatset_cleaning:
    cmd: python .\src\data\step_2_Independent_HousesDatset_cleaning.py .\data\raw\independent-house.xlsx
    deps:
    - .\src\data\step_2_Independent_HousesDatset_cleaning.py
    - .\data\raw\independent-house.xlsx

   step_3_merge_flats_and_house:
    cmd: python .\src\data\step_3_merge_flats_and_house.py .\data\processed\
    deps:
    - .\src\data\step_3_merge_flats_and_house.py
    - .\data\processed\
   
   
